
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 03 00:13:50 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 20;
  public static final int CONST = 5;
  public static final int GE = 25;
  public static final int LPAREN = 40;
  public static final int SEMI = 38;
  public static final int CONTINUE = 13;
  public static final int BINOR = 31;
  public static final int MINUS = 36;
  public static final int FOR = 12;
  public static final int RPAREN = 41;
  public static final int LS = 24;
  public static final int COMMA = 39;
  public static final int CLASS = 7;
  public static final int INC = 33;
  public static final int BINAND = 32;
  public static final int DIV = 29;
  public static final int PLUS = 35;
  public static final int IF = 9;
  public static final int DOT = 27;
  public static final int LE = 26;
  public static final int ABSTRACT = 8;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int EQUAL = 37;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int NUMBER = 17;
  public static final int MOD = 30;
  public static final int BREAK = 6;
  public static final int IDENT = 18;
  public static final int VOID = 15;
  public static final int SAME = 21;
  public static final int LBRACE = 42;
  public static final int ELSE = 10;
  public static final int LSQUARE = 44;
  public static final int READ = 14;
  public static final int RSQUARE = 45;
  public static final int RBRACE = 43;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 19;
  public static final int DIFF = 22;
  public static final int DEC = 34;
  public static final int GT = 23;
  public static final int PRINT = 3;
}

